### ISSUE TITLE
[BUG] additional_params not working

### ISSUE THREAD

**Issue by alex46300** [Checkmarx/ast-github-action#28]
### Describe the bug
The param "additianal_params" is not working in a scan

### Expected behavior
it is important to be able to configure the scan like with cxflow :
https://github.com/checkmarx-ts/checkmarx-cxflow-github-action

### Part of workflow.yml

```
- name: Checkmarx AST Github Action
  uses: Checkmarx/ast-github-action@main
  with:
    project_name: ${{ github.event.repository.name }}
    cx_tenant: ****
    base_uri: ****
    cx_client_id: ${{ steps.secrets.outputs.client-id }}
    cx_client_secret: ${{ steps.secrets.outputs.client-secret }}
    # scan_types: sast,kics,sca 
    additional_params: >-
      --tags product_id:123456789-123456-789654123
```

**Comment by jbrotsos** [comment]
Hey @alex46300 ,

Is the scan failing or is the tag just not being created?

Thanks,
James

**Comment by alex46300** [comment]
Hi @jbrotsos ,

The scan works but there is no documentation about additional_params (how to configure the thresholds, an incremental scan...?) 
Yes tag is not created but it is just one example of additional_params.

Thanks,
Alexis

**Comment by jbrotsos** [comment]
Documentation can be found here:

https://checkmarx.atlassian.net/wiki/spaces/AST/pages/5908135977/CxAST+GitHub+Action+Configuration+Variables

It references: https://checkmarx.atlassian.net/wiki/spaces/AST/pages/3080194906/scan+create

I do agree we should highlight this more.

**Comment by jbrotsos** [comment]
@pedrompflopes can you investigate if tags is not working?

**Comment by pedrompflopes** [comment]
@jbrotsos  yes I will have a look

**Comment by pedrompflopes** [comment]
Hey @alex46300  

We couldn't recreate the bug. The --tags is used for scan tags, is that what you are looking for? 

![image](https://user-images.githubusercontent.com/83576881/153007393-c4f59a38-392b-4882-aa7b-b79e3d335565.png)

Thanks.

**Comment by alex46300** [comment]
Thanks for your response @pedrompflopes 

Ok tags are only applied on scans and not applied on project tags. I misunderstood sorry.

However, I have other problems with other additinal_params. Maybe could you mitigate my syntax if I am wrong. When I add 
`--threshold sast-high=1` or `--sast-incremental true` the scan is not started : 

```
- name: Checkmarx AST Github Action
  uses: Checkmarx/ast-github-action@main
  with:
    project_name: ${{ github.event.repository.name }}
    cx_tenant: ****
    base_uri: ****
    cx_client_id: ${{ steps.secrets.outputs.client-id }}
    cx_client_secret: ${{ steps.secrets.outputs.client-secret }}
    # scan_types: sast,kics,sca 
    additional_params: >-
            --threshold sast-high=1
            --tags product_id:123456789-123456-789654123
            --sast-preset-name "High and Medium"
            --sast-incremental true
```

Could you please help me ?
