### ISSUE TITLE
[BUG] Launch scan on push code event not working

### ISSUE THREAD

**Issue by alex46300** [Checkmarx/ast-github-action#30]
### Describe the bug
When I commit code on the master branch, the scan does not start.
On the other hand, the scan starts perfectly when I create a PR.

### Steps to reproduce

Part of workflow.yml

```
name: Checkmarx AST Scan  
on:
  pull_request:
    types: [opened, reopened, synchronize] #Types specify which pull request events will trigger the workflow. For more events refer Github Actions documentation.
  push:
    branches:
      - main
      - master
      - dev
```
