### ISSUE TITLE
[REQ] Sample with API Key as a credential

### ISSUE THREAD

**Issue by kfeeley** [Checkmarx/ast-github-action#69]
### Is your request related to a workflow problem?
Getting started with using an API Key as a credential was tough. I was able to get things working by looking at the CLI parameters and the solution ended up being very simple.

### Propose a solution
I can open a PR containing the sample YAML.

```
name: Checkmarx AST Scan
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          base_uri: https://ast.checkmarx.net/
          cx_tenant: your_tenant
          additional_params: --apikey ${{ secrets.CX_API_KEY }}
```

### Additional comments
This is not a change to the action itself, but just the addition of a sample, like the ones here: https://github.com/Checkmarx/ast-github-action/tree/main/sample-yml
